baseURL = "https://kapani.xyz"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "twenty-twenty-hugo"
title = "Kapani IT"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "sample-page"
name = "Sample Page"
weight = 5
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Kapani IT"
description = "This is meta description"
[params.banner]
heading = "Kapani IT Systems and Solutions"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "Get our latest updates here."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Contact us for more information. We strive to respond within 4 working days."
enable = true
title = "Contact us."
[params.cookies]
enable = true
expire_days = 2
[params.footer]
address = ""
content = "Made in BANGLADESH"
copyright = "Copyright &copy; 2020 Kapani IT Systems and Solutions"
hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"
title = "Kapani IT"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "#"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
